version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./var/lib/postgresql/data
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

